language: cpp
compiler:
        - clang
        - gcc

before_install:
        - sudo apt-get update
        - sudo apt-get install xorg-dev libglu1-mesa-dev x11proto-xf86vidmode-dev

install:
        - wget https://github.com/glfw/glfw/archive/3.0.4.tar.gz
        - tar -xzvf 3.0.4.tar.gz
        - pushd glfw-3.0.4/
        - cmake .
        - make
        - sudo make install
        - popd
        - sudo apt-get install libglm-dev

before_script:
        - pushd build/

script:
        - cmake ..
        - make

after_script:
        - popd

env:
  global:
   - secure: "<removed>"

addons:
  coverity_scan:
    project:
      name: "OpenBTG/openbtg"
    notification_email: <removed>
    build_command_prepend: "cd build && make clean"
    build_command: "make"
    branch_pattern: coverity_scan
