name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_test:
    name: build_test
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: before_install
        run: |
         sudo apt update
         sudo apt install -y xorg-dev libglu1-mesa-dev x11proto-xf86vidmode-dev
      - name: install
        run: |
         wget https://github.com/glfw/glfw/archive/3.0.4.tar.gz
         tar -xzvf 3.0.4.tar.gz
         pushd glfw-3.0.4/
         cmake .
         make
         sudo make install
         popd
         sudo apt install -y libglm-dev
      - name: before_script
        run: pushd build/
      - name: script
        run: |
         cmake .
         make
      - name: print_result
        run: |
         ls -lah ./build
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: openbtg_build_artifacts
          path: ./build
